[package]
name = "api_utils"
edition = "2021"
version = "0.1.0"

[dependencies]
db = { path = "../db" }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["raw_value"] }
vercel_runtime = "1.1.6"
